name: Publish a Swift Async/Await release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-swift-async-await'
jobs:
  publish-cocoapods-libraries:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.2-beta'
      - run: pod trunk push KMPNativeCoroutinesAsync.podspec --synchronous
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}