name: Run Swift tests
concurrency:
  group: run-swift-tests-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
env:
  XCODEBUILD_DESTINATION_iOS: platform=iOS Simulator,name=iPhone 12 Pro Max
  XCODEBUILD_DESTINATION_macOS: platform=OS X
  XCODEBUILD_DESTINATION_tvOS: platform=tvOS Simulator,name=Apple TV
  XCODEBUILD_DESTINATION_watchOS: platform=watchOS Simulator,name=Apple Watch Series 7 - 45mm
jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11 ]
        xcode: [ 13.1 ]
        platform: [ iOS, macOS, tvOS, watchOS ]
        implementation: [ Combine, RxSwift ]
    name: ${{ format('{0} {1} ({2}, Xcode {3})', matrix.implementation, matrix.platform, matrix.os, matrix.xcode) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - name: Run tests
        env:
          XCODEBUILD_SCHEME: ${{ format('KMPNativeCoroutines{0}', matrix.implementation) }}
          XCODEBUILD_DESTINATION: ${{ env[format('XCODEBUILD_DESTINATION_{0}', matrix.platform)] }}
        run: >-
          xcodebuild test
          -project KMPNativeCoroutines.xcodeproj
          -scheme "$XCODEBUILD_SCHEME"
          -destination "$XCODEBUILD_DESTINATION"