name: Run Kotlin tests
concurrency:
  group: run-kotlin-tests-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - kotlin/**
jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11 ]
        java: [ 11 ]
        module: [ core ]
    name: ${{ format('{0} ({1}, JDK {2})', matrix.module, matrix.os, matrix.java) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
      - name: Cache Gradle
        uses: ./.github/actions/cache-gradle
      - name: Cache Konan
        uses: ./.github/actions/cache-konan
      - name: Run tests
        env:
          GRADLE_MODULE:  ${{ format(':kmp-nativecoroutines-{0}', matrix.module) }}
        run: ./gradlew $GRADLE_MODULE:allTests